### ISSUE TITLE
resize google play store and apple store buttons

### ISSUE THREAD

**Issue by DelgadoJorge** [asu-cis-capstone/uvents#15]

**Comment by ghost** [comment]
I believe I can help with this task. What size do you need them to be?

**Comment by DelgadoJorge** [comment]
I'm not too entirely sure on the exact width and length. But I would guess
80% of its current size. Thanks Mark.

**Comment by ghost** [comment]
Ok, I have a good image resizing program. I'll try to reduce all of the
apple icons to 80% by tomorrow or Saturday.
