### ISSUE TITLE
Size down app link images on homepage

### ISSUE THREAD

**Issue by ptamang1** [asu-cis-capstone/uvents#20]

**Comment by sngunawa** [comment]
I looked at some websites to see the appropriate sizes for a “find it on the app store” picture. They were all pretty small. Using Target as an example, I got two pictures that you can use. The size for the “App Store” should be around 277 x 82 and one for the “Google play” should be 230 x 80. I have the two images here and the Target screenshot.

![app_store_new](https://cloud.githubusercontent.com/assets/10620640/7218119/94a5425c-e60f-11e4-81e5-eccfed0165cd.jpg)
![google_play_new](https://cloud.githubusercontent.com/assets/10620640/7218122/97db777a-e60f-11e4-94fe-1234ee536eaf.jpg)
![example2](https://cloud.githubusercontent.com/assets/10620640/7218124/9be85bf8-e60f-11e4-944e-a550cb42404c.png)

**Comment by ptamang1** [comment]
This looks great, thanks!
